### ISSUE TITLE
Comments from G.Claus

### ISSUE THREAD

**Issue by clausg67** [eudaq/StatusTelescope2015-Paper#10]
Dear Hendrik,

Please find hereafter my comments
- Additionnal information about DAQ architecture, I propose to rewrite the paragraphe starting on page 6 line  16 + references on EUDET memo, NI talk and paper on DAQ architecture
- Info about the area of AIDA Telescope planes, Page 14, line 12

Cheers,
Gilles.

Page 6, lines 16 to 24

The MIMOSA 26 sensors generate zero-suppressed hit data over a ribbon cable to the auxiliary boards, which provide RJ45 connectors to connect with the data concentrator board collecting the data from all six sensors and the trigger/busy lines from the TLU.
The signals from concentrator board (sensors data and TLU) are acquired by a COTS (Components
Off The Shelves) DAQ system built around the National Instrument (NI) PXIe crate architecture. The NI FlexRIO board (PXIe 7962R) acquires and deserializes the 12 serial links at 80 Mb/s, detects triggers and reads the TLU, all these processings are done by a  firmware running on a Virtex 5 FPGA embeded on the FlexRIO board. The resulting data stream of 960 Mb/s (120 MB/s) is read by the CPU (PXIe 8130) from the PXIe bus via a DMA channel and processed on-line by software : frames with trigger selection and data formatting. The data are then available to EUDAQ framework, an event is written to disk in normal handshake mode, only if a trigger has been raised for a certain telescope readout frame. This  co-developement method sharing processing tasks between firmware and sofware allows to high flexibility for system upgrade. This DAQ architecture is able to read 6 Mimosa 26 sensors without any dead-time at up to 8680 frames/s and has been sucessfully upgraded for the AIDA Telescope equipped by 12 Mimosa 28 sensors, which translates to 24 links at 160 Mb/s. More details are available in Ref [x,y].

[x] G.Claus et al. IPHC & NI Flex RIO DAQ for EUDET Mimosa 26 Beam Telescope, Eudet-Memo-2010-25. http://www.eudet.org/e26/e28/e86887/e106215/EUDET-Memo-2010-25.pdf

[y] G.Claus, C.Santos. Data acquisition system based on NI COTS for pixels sensors characterization in beam test. National Instrument Big Physics Symposium - Austin Texas - 1,August 2011.
Paper : http://www.iphc.cnrs.fr/IMG/pdf/Paper__IPHC_PICSEL_BP_Austin_2011_gc_v10.pdf
Talk : https://decibel.ni.com/content/docs/DOC-17573

Page 14, line 12

"A quad plane comprising four Mimosa 28 planes will enlarge the acceptance window."

Add the area information

A quad plane comprising four Mimosa 28 planes, has been built for the AIDA telescope, covering a detection area of 16 cm², it will enlarge the acceptance window."

**Comment by TCThenna** [comment]
Dear Gilles, thanks a lot for your comments!

I have only few questions/comments regarding your comments:

> The resulting data stream of 960 Mb/s (120 MB/s) is read by the CPU (PXIe 8130) from the PXIe bus via a DMA channel and processed on-line by software : frames with trigger selection and data formatting. 

I don't understand the part after the ":". What kind of data formatting is taking place? What exactly does the on-line software?

> ... and has been sucessfully upgraded for the AIDA Telescope equipped by 12 Mimosa 28 sensors, which translates to 24 links at 160 Mb/s. 

This paper is not about the AIDA telescope, so we try to not mix AIDA with EUDET. This additional information about the quad plane should only be mentioned on page 14, as you also suggest later in your comment.

**Comment by clausg67** [comment]
> I don't understand the part after the ":". What kind of data formatting is taking place? What exactly >does the on-line software?

The FlexRIO board FW deserialize data on each of the two Mi26 serial link, but it doesn't take care about data frame building which is multiplexed between the two links, this is done by SW. Moreover, there is one more level demultiplexing done by SW it is between sensors, the FlexRIO DRAM doesn't contain the data from Mi26 in consecutive segments from Mi26 No 0 to No 5, they are also multiplexed. Last, but not least ... all the frames coming from Mi26 are deserialized and stored in FlexRIO DRAM regardless of the fact that they contains or not a trigger, and full frame length is stored regardless of the hits number. Therefore frames with trigger selection is done at SW level, and also frames truncation to remove the part without hits and save only the useful data. That's what I call "co-developement" between FW & SW, I have taken this decision in order to minimize FW complexity, save development time and it was possible thanks to the performances of the NI CPU. I had also in mind the risk to loose my FW engineer, and this has been the case ... but I have managed to upgrade this DAQ and fix bugs without any FW modification during 4 years, thanks to the processing part done by SW which I am able to modify myself. The first FW upgrade of the DAQ has been done this year to move to LabVIEW 2014 and also fix minor FW bugs, solved by SW work-around before ;-).

**Comment by clausg67** [comment]
> This paper is not about the AIDA telescope, so we try to not mix AIDA with EUDET. This additional >information about the quad plane should only be mentioned on page 14, as you also suggest later in >your comment.

Ok, I agree, no problem

**Comment by TCThenna** [comment]
ah ok, I undestand better know. I learned just now  that "co-developement" seems to be a standard term for those dealing with interfaces of FW to SW level, but I am not if the regular reader (a telescope user) knows what "co-developement" is. 

Long story short: I will replace the paragraph from page 6, lines 16 to 24 with your paragraph, with only slight changes to make all readers happy. 

I'll also add the references. 

On page 14 I'll add a sentence about the quad planes.

thanks again!
