### ISSUE TITLE
comment from M.Goffe

### ISSUE THREAD

**Issue by mgoffe** [eudaq/StatusTelescope2015-Paper#11]
Dear Hendrik,

In page 3 when you describe the mimosa26 sensor, I have a remark or a reminder:

The sensor mimosa26 was produced on four different epitaxial layers:
 In standard epitaxial layer => Low resistivity (~20 Ohm.cm) with a thickness of 14um
and in High-Resistivity epitaxial layer => Hi-Res (~400 Ohm.cm) with a thickness of 10, 15 & 20um (which increase the charge collection and have a better tolerance to not ionizing radiation)

In the sensors provide to DESY to build the telescope only the first set (for the prototype for the integration) has an epitaxial layer of 14µm (and low-resistivity) and it was with unthin sensors (~700 µm).
But for the different telescope which was put in beam it is the thin sensors at 50um with High-resistivity.

And not all the telescope has the same epitaxial layer thickness:
By example the DESY and Bonn telescope (ANEMONE) are equip with 10um, the ATLAS telescope (ACONITE) and DATURA with 20um and the last set I provide in April is in 15um.

Best regards
Mathieu

**Comment by TCThenna** [comment]
Dear Mathieu,

thanks for your valuable comment. Actually, we were searching for information on exactly this topic during the last days (see comments from Igor. In my last reply, first point, I think). So I will correct to the paper to read "HR 20um".

What a coincidence, that ACONITE and DATURA have the same thickness, so they also should have a very comparable intrinsic resolution, since these are the two telescopes that we use data from.

**Comment by TCThenna** [comment]
Ah, one more question:

On page 2 line 38ff, we write: "The results reported here are based on data taken with $\Datura$ at test beam area~21 at {DESY-II} and with ACONITE at SLAC~ESTB and SPS~H6, but are applicable to all other copies. "

In your opinion, by how much does the intrinsic resolution change with epi thickness? Might it be, that our results are only valid for DATURA and ACONITE?

Do you know the thickness of the sensors in the AIDA telescope (which at the moment is still equipped with Mimosa 26 sensors) ?

**Comment by TCThenna** [comment]
I close the issue as this dependence will not be added to the paper.
