### ISSUE TITLE
Comments from Hanno

### ISSUE THREAD

**Issue by hperrey** [eudaq/StatusTelescope2015-Paper#7]
Hej telescope team,

thank you for this detailed, thorough and well-written paper -- it was a pleasure to read! :)

So my comments really boil down to some nit-picking concerning wording; the only two general comments I have would be:
- I appreciate how you factorize the original EUDET telescope from the (still ongoing) developments towards the next-generation family of telescopes -- this gives a well-defined reference point. The only aspect where this factorization breaks down somewhat is when it comes to EUTelescope: specifically, I don't think we really have had a version with fully-working GBL support before summer last year. So the work that went into this was done e.g. by Igor, Denys, Phill, Tobias (no particular order here). I guess you have already discussed this on-site, but maybe one could include citations to the corresponding theses? And then have a dedicated EUTelescope paper later.
- again concerning the factorization: you give an outlook to EUTel/EUDAQ and telescope developments; there would be the option to cite e.g. two TIPP proceedings of 2014 that Igor and I wrote (or the IEEE proceedings from 2013) for details (and some other I forgot) -- just to consider.

Now, into the nit-picking (please treat anything affecting wording/language as suggestion only!):
- p1, l3: my main affiliation is with "Lund University, Sweden", not with ESS
- p1, l15: "software _packages_ are available"
- p1, l16: "_the_ common data acquisition framework"
- p2, l15: "_Such_ studies are well _suited_ and often used for ..." -> has a slightly better flow imho
- p2, l35: "_software_ framework"
- p2, l37: I think "From ... until ... alone, ...." reads better
- p4, figure: potentially have one of the colored boxes with dots/dashes instead (for clarity); and maybe use lighter turquoise?
- p5, l26: "cross platform" -> "cross-platform"
- p5, l27: "simple to use" -> "simple-to-use"
- p6, l13: "Basic sanity checks such as the event numbers from ..." -> "Basic sanity checks such as testing the consistency of event numbers reported by the individual subdetectors ..."
- p6, l19: "is rendered possible" -> "is possible during run-time" or "data-taking" ?
- p6, l37: "builds on" -> "is based on" ('build' is repeated in the next line)
- p6, l53: ".. simple straight line fit provides maximum performance" -> "... simple straight line fit provides sufficient precision and a maximum of computational performance"
- p7, l1: "implements" -> "utilizes"/"utilises" : we do not really implement any algorithm of Millipede-2 since we are using the implementation provided by the author and just interface to it.
- p7, l3: "jobsub" reads a little strange in the middle of the sentence; maybe use italics for the first mentioning of it? Or capitalize it?
- p14, l40: "eudet-jra1" should be uppercase
- p15, l3: the TLU user manual has also been published as EUDET memo (of which you cite several) -- maybe prefer that over the link?

**Comment by TCThenna** [comment]
Hey there, thanks a lot for the comments!

quick answer to the general comments:
- Glad that you like the idea. It gives us the possibility to write this paper without having to finish the development first ;) The EUTelescope version used is 0.9x, if I remember correctly. Isnt GBL part of the 1.x stuff? So, we use straight line fits on the one hand, and on the other we dont go much into detail concerning the EUTelescope section. And as you have guessed, we will start an EUTelescope paper next week. Could please PM me the emai of Denys?
  So do you think it is still a problem although we are not using 1.x ?
- Uff, yes, of course. Sry for not having thought of this! Please PM me the doi of the IEEE proceeding. The TIPP ones I have.

**Comment by rubinsky** [comment]
Hanno, 
the EUTelescope reference is a weak point indeed. One of the options would be to have the AIDA Note on the EUTelescope published on Arxiv turned into a JINST paper with all relevant people on the author list

**Comment by hperrey** [comment]
@TCThenna There had been an interface to GBL in 0.9.x, but it was not really generically usable. For this, quite a lot of additional work had been needed. So for the "original" EUDET telescope, GBL had not been a part of EUTelescope, and strictly speaking there is still no formally released version with full support of GBL.
But in a way, this is a little pedantic -- as long as all contributors are mentioned in some form, I am fine with however you choose to handle this. For the EUTel paper I would strongly argue for a proper release of EUTel with GBL though!

By the way: I really appreciate going the Open Access route with the publication!
That reminds me of two additional comments:
- one could mention EUDAQ (and hopefully soon EUTel?) being GPL-licensed 
- you could mention the telescopes portal site https://beam-telescopes.desy.de as this collects all information regarding the telescopes

@rubinsky I _knew_ I was forgetting a (or _the_?) key person!

**Comment by simonspa** [comment]
Was the EUDAQ move to GPL ever finished? I just remember the mail and stone w answers but no code changes etc.

Richard and I will release EUDAQ 1.5 in a few weeks - maybe that would be time for a proper transition...

Am 12. Mai 2015 14:39:08 MESZ, schrieb Hanno Perrey notifications@github.com:

**Comment by simonspa** [comment]
Hi @hperrey and @rubinsky 
the EUTelescope version referenced and used is 0.9.3 dating back to Jan. 17 2014. Thus, no formal GBL tracking processor is provided, but several groups (CMS Pixel e.g.) already use their own GBL implementation since years. This drove us to put this one single mentioning of GBL into Section5 - but that could of course be removed if desired.

EUTelescope 1.0 will be subject to a dedicated paper going all into the details of various alignment and tracking possibilities - then of course also including the very active authors of the software starting from Feb. 2014.

Cheers,
Simon

**Comment by hperrey** [comment]
@simonspa Thanks for the clarifications! I am absolutely fine with the decision to factorize the telescope (software) components like this and just wanted to avoid advertising features not (yet) included ;)

Also, EUDAQ is under GLPv3, at least the version in the master branch is: https://github.com/eudaq/eudaq/blob/master/LICENSE.md
However, I have not modified e.g. file headers and such -- feel free to do so for any future release! We have had the ok from all authors to go forward with this change.

**Comment by hperrey** [comment]
@simonspa Ah, and here is the corresponding pull request for the license change: https://github.com/eudaq/eudaq/pull/80

**Comment by simonspa** [comment]
Nice, I even merged it myself... :)
Okay I guess I was mislead by the file headers. We are thinking about a
code beatification anyways and might add it alongside.

Thanks!

**Comment by simonspa** [comment]
We are citing the TLU user manual because the Memo is terribly outdated and does not provide further information (it references TLU v0.1a)
