### ISSUE TITLE
Comments from Igor

### ISSUE THREAD

**Issue by rubinsky** [eudaq/StatusTelescope2015-Paper#8]
I agree that its a real pleasure to see this paper at a near complete state. Thanks to everyone involved!
Please see my comments below.

While looking through the plots I was puzzled about few things, minor or major, pls judge yourself: 
Fig.4. 
---  do you have a reason for limiting yourself to 90% of the peak width? not 95 or anything else? how the result would change? could you please provide the mean/RMS values from the measurement and the fit in a table? how good is the chi2 of the fit?
Fig.5. 
--- could you show same plot for all thresholds and energies?
--- did you rerun the track fit for the newly obtained intrinsic resolution of the Mimosa26 sensors? The flat.vs.smilie behaviour in the prediction.vs.measurment is typical for wrongly assumed Mimosa26 intrinsic resolution in the track fit. in the extreme case the two next to the end points are significantly lower then the internal ones, this is much more visible on the unfolded pointing resolution plot. The caption should state something like - the track fit was redone iteratively for convergence check.
Fig.6.
--- a) there is strong systematic drift of the lower energy measurements compared to the higher energies. why? at a first glance it looks like you are cutting into the residuals or the track chi2, so for the lower energies you get fewer track fit - DUT point match.
--- overall, is it the same data we took 2 years ago or it is the new data? the data we were using was taken in TB21 where the beam energy was off by 20%, so the energy labels should have read 2.4, 3.6, 6.0 GeV.

**Comment by TCThenna** [comment]
Dear Igor, thanks for your comments.
- Fig4 : As is written in the text: "It is noted, that the residuals feature non-Gaussian tails, as is expected from the underlying physics of the scattering mechanism [22]." I.e. there are tails from Rutherford scattering, that are NOT included in the Rosenbluth formula. The Rosenbluth formula is valid for the central 98% of the data (see PD-Booklet, section 32, equation (32.15)). Using 98% doesnt change the width. We wanted to stay away from the transition region to Rutherford scattering, so chose something a bit smaller than 98%. An addtional 4% on each side translate to something like icreasing the width by 0.2 um on each side... You can also ALWAYS use the RMS of all residuals, and define this as your resolution. In the end, one needs to be consistent and clear about what one defines as your resolution, which is, I think, what we did.
  mean/RMS: The mean is compatible with 0, we dont quote RMS of the distribution (see above), and we DO quote the fit result on the width next to the plot. Please explain why you want the reader to know mean and RMS. Maybe we can understand what you are after.
  I agree with adding the chi2 to the plot. In case the majority agrees on also adding the zero-compatible mean, then I'd also go for adding a table.
- Fig. 5 - 1): Can you please explain what the gain is for the reader to have these plots for all energies and thresholds? we have measured at ~5 energies, 2 configurations (wide and narrow) and 10 thresholds, which adds up to 100 plots.
- Fig. 5 - 2) I dont completely understand your question. With "The two next to the end points", you mean plane 1 and 4 ? In which extreme case their resolution is predicted wrongly? In both the prediction AND the measurement we get the smilie plot, i.e. an increased unbiased residual width for plane 0 and 5.
  I'll check with Thomas if the track-fit was re-done. Or which resolution he assumed in the first place.
- Fig. 6 - a) first of all, the spread within each threshold is less than 0.5% around the central value (between 0.985 and 0.995), which is already quite astonishing. Yes, there are some systematics inside this spread. However, we are not planning to investigate on this 5 per mile effect. The chi2 cut on the tracks is VERY high, so we are most likely not cutting away anything. Also, we look for hits within 100 um of the extrapolated position on the DUT, which includes also larger scattering angles.
- Fig. 6 - overall) Good thinking, I'll double check with Thomas to be 100% sure about the labels!!

**Comment by rubinsky** [comment]
> On 12 May 2015, at 16:19, TCThenna notifications@github.com wrote:
> 
> Dear Igor, thanks for your comments.
> 
> Fig4 : As is written in the text: "It is noted, that the residuals feature non-Gaussian tails, as is expected from the underlying physics of the scattering mechanism [22]." I.e. there are tails from Rutherford scattering, that are NOT included in the Rosenbluth formula. The Rosenbluth formula is valid for the central 98% of the data (see PD-Booklet, section 32, equation (32.15)). Using 98% doesnt change the width. We wanted to stay away from the transition region to Rutherford scattering, so chose something a bit smaller than 98%. An addtional 4% on each side translate to something like icreasing the width by 0.2 um on each side... You can also ALWAYS use the RMS of all residuals, and define this as your resolution. In the end, one needs to be consistent and clear about what one defines as your resolution, which is, I think, what we did.
> mean/RMS: The mean is compatible with 0, we dont quote RMS of the distribution (see above), and we DO quote the fit result on the width next to the plot. Please explain why you want the reader to know mean and RMS. Maybe we can understand what you are after.
> I agree with adding the chi2 to the plot. In case the majority agrees on also adding the zero-compatible mean, then I'd also go for adding a table.
> 
> I think its a good move to open this information to the authors. You have this information somewhere, just attach as a pdf to this paper as supplement material.
> 
> Fig. 5 - 1): Can you please explain what the gain is for the reader to have these plots for all energies and thresholds? we have measured at ~5 energies, 2 configurations (wide and narrow) and 10 thresholds, which adds up to 100 plots.same

same argument, pls show the plots.

> Fig. 5 - 2) I dont completely understand your question. With "The two next to the end points", you mean plane 1 and 4 ? In which extreme case their resolution is predicted wrongly? In both the prediction AND the measurement we get the smilie plot, i.e. an increased unbiased residual width for plane 0 and 5.
> I'll check with Thomas if the track-fit was re-done. Or which resolution he assumed in the first place.
> 
> yes, I am talking about plane 1 and 4, they hang down stronger if the intrinsic resolution in the fit is smaller then it should be.
> Fig. 6 - a) first of all, the spread within each threshold is less than 0.5% around the central value (between 0.985 and 0.995), which is already quite astonishing. Yes, there are some systematics inside this spread. However, we are not planning to investigate on this 5 per mile effect. The chi2 cut on the tracks is VERY high, so we are most likely not cutting away anything. Also, we look for hits within 100 um of the extrapolated position on the DUT, which includes also larger scattering angles.
> 
> the discrepancy between the efficiencies should be given in the errors assigned to each point which are smaller then the point markers, so they are smaller then 0.1% (what are they?), and the disagreement between 0.985 and 995 is at least 10 sigma. In order to make the points agree one has to introduce a systematic error to make them agree. My question was where does this come from and how to describe this properly.
> 
> Fig. 6 - overall) Good thinking, I'll double check with Thomas to be 100% sure about the labels!!
> 
> —
> 
> one more general question, do all Mimosa sensor have same epitaxial thickness? in all our telescopes we had two sets of the sensors, one with 10 um and the second with 20 um epi thickness, the most important thing in all this, is that their intrinsic resolution dependence on the threshold is different.

**Comment by TCThenna** [comment]
> I think its a good move to open this information to the authors. You have this information somewhere, just attach as a pdf to this paper as supplement material.

I agree that this can be a supplement material. EPJ TI supports supplement material that can be accessed online.

> same argument, pls show the plots.

Again, please explain, what additional information the reader gains by including these plots. I just dont see where adding these 98 plots -- even to the supplement material -- justifies the work to prepare them in the paper style. We could also add ALL unbiased residual plots for all planes, thresholds, energies and configurations, adding to something like 1200 plots. For good reasons, we are not doing this either.

> the discrepancy between the efficiencies should be given in the errors assigned to each point which are smaller then the point markers, so they are smaller then 0.1% (what are they?), and the disagreement between 0.985 and 995 is at least 10 sigma. In order to make the points agree one has to introduce a systematic error to make them agree. My question was where does this come from and how to describe this properly.

At the moment, the origin of this is not completely understood. Please note that this is the average of all 6 sensor planes. With less pointing resolution on plane 0 and 5, the spread in efficiency might be dominated by plane 0 and 5 for each threshold. Also I can imagine that the alignment can change on the per mile level between runs. 
In the paper, we state that the statistical error on the efficiency is negligible, the systematic ones are also probably negligible. We just dont completely understand everything down to the few per mile level. So maybe, it is not an uncertainty on the measurement, but a weakness of the model. This doesn't justify to enlarge error bars just to explain a systematic spread. What you are referring to with your 10 sigma just means, that it is unlikely to be a statistical outcome, with which we all agree. But again, it is likely, as you say, a (not well understood) systematic. 
-->> Hints on what it is are welcome ;)

> one more general question, do all Mimosa sensor have same epitaxial thickness? in all our telescopes we had two sets of the sensors, one with 10 um and the second with 20 um epi thickness, the most important thing in all this, is that their intrinsic resolution dependence on the threshold is different.

I was under the impression that the epitaxial layer is 14 um. This is what you write in your 2011 TIPP proceedings:
"The sensors implemented in the telescope were manufactured in a 0.35 μm CMOS process and a 14 μm thick epitaxial layer. " Why should it be 10 or 20 then?

We'll look into the energies used. We have to dig a little first.

**Comment by rubinsky** [comment]
there is no need to add the plots and tables to the paper, just attach them to the discussion please (in any convenient form)

**Comment by rubinsky** [comment]
> one more general question, do all Mimosa sensor have same epitaxial thickness? in all our telescopes we had two sets of the sensors, one with 10 um and the second with 20 um epi thickness, the most important thing in all this, is that their intrinsic resolution dependence on the threshold is different.
> 
> I was under the impression that the epitaxial layer is 14 um. This is what you write in your 2011 TIPP proceedings:
> "The sensors implemented in the telescope were manufactured in a 0.35 μm CMOS process and a 14 μm thick epitaxial layer. " Why should it be 10 or 20 then?

hi Hendrik,

the epi layer thickness I got from the Sbg experts are:
Chips 55/65 66 67 68 69 72 are in epitaxial layer HR10 um.
Chips 73 74 75 76 77 79 tel:74%2075%2076%2077%2079 are in HR 20 um.

pls check which ones were installed for the data analysed, the easiest check is to make sure that the average cluster size (in X or in Y) is similar for all six sensors. different thickness leads to different cluster size, which leads to different intrinsic resolution. If I remember it right, it was only in ACONITE that we had a mix of two types of sensors, but pls double check this for the data that goes into the paper.

**Comment by rubinsky** [comment]
> I was under the impression that the epitaxial layer is 14 um. This is what you write in your 2011 TIPP proceedings:
> "The sensors implemented in the telescope were manufactured in a 0.35 μm CMOS process and a 14 μm thick epitaxial layer. " Why should it be 10 or 20 then?
> 
> this was written for the final EUDET telescope (year 2010), the sensors are now with the AIDA telescope in H6B. If the write-up claims it’s 14 um, then it’s 14. If we do have any data from this telescope going into the paper, this should be double- checked as well. But we don’t, do we?

**Comment by TCThenna** [comment]
no, there is no data from AIDA telescope going in. I'll check the numbers of the Mimosa sensors!

**Comment by dreyling** [comment]
At DATURA, there are now installed 

sensor 73   in frame, now plane 0
sensor 74   in frame, now plane 1
sensor 75   in frame, now plane 2
sensor 76   in frame, now plane 3
sensor 77   in frame, now plane 4
sensor ?    in frame connected to Aux 0903 TE, now plane 5

I guess 79 for the ?, however, it is not written outside

**Comment by TCThenna** [comment]
I'll try to summarise what's left to do:
- double check that epi thickness is 20 um
- add chi2 to plots, add to text that mean is within alignment uncertainty of 0.1 um
- re-run track fit for a run with high threshold assuming a larger \sigma_int and see if track parameters and/or smilie plot changes
- We look again into systematics for FIg 6(A)
- "energy labels"/energy actually used

**Comment by TCThenna** [comment]
- The thickness is 20 um for DATURA and ACONITE, thinner for other telescopes. I am waiting for Mathieu to answer how big an effect this can have on resolution.
- I added the chi2 value to the plot,
- Thomas re-ran the analysis. There is no effect on the track parameters when re-running with different \simga_int. Of course, chi2 changes, but not the track parameters themselves by a more than negligible amount.
- Efficiency: The plot WAS a mean value of all six planes. We change this now and show only the efficiency for plane 3. This makes sense: The efficiency of the 6 Mimosas is almost the same for every sensor, but the position (the 2 outer sensors) defined most strongly the "distance from 100%". We are now at 99.5% efficiency at threshold 6, the spread is 0.2%. The data of the outlier (I am talking of an outlier on the 0.1% basis ...) was taken three months later. So there was something a bit different in the beam/environment/whatsoever, that resulted in an added inefficiency of 0.1%. 
- The energy labs have to be corrected. There was a bug in the magnet current software during the time of the data taking. The offset is about 20%.

I'll commit the changes, and go for submission soon. 

I close the issue if no one objects.

**Comment by rubinsky** [comment]
hi Hendrik,

the plots were not provided yet, the paper co-authors can not follow the whole analysis chain. as I mentioned earlier, they have full right to see all intermediate plots based on which the final plots are made.

the effect from different epi layer thickness is big, we measured it with this “telescope data" the cluster-size.vs.resolution.vs. threshold for different epi layer thickness with our data and the double thickness leads to roughly double the cluster-size (square). These plots were on afs with the analysis scripts. The threshold dependence is different (parabola like in one case and pretty much flat in the second). Could you repeat this plot as a cross check?

**Comment by TCThenna** [comment]
Additional plots have been posted here: 

StatusTelescope2015-Paper/additional_eps/
So you can have a look at 100 smiley plots.

I thought this addition was posted, I just saw that we didnt mention it explicitly, sry for that.

If the difference is big (see open issue from Mathieu with my question about this), we have to change this sentence from:

The results reported here are based on data taken with $\Datura$ at test beam area~21 at {DESY-II} and with ACONITE at SLAC~ESTB and SPS~H6, but are applicable to all other copies. 

to 

The results reported here are based on data taken with $\Datura$ at test beam area~21 at {DESY-II} and with ACONITE at SLAC~ESTB and SPS~H6, but are applicable to all other copies with the same sensor thickness \cite{}. So we add a citation of the new TWiki which will have a section on every single telescope listing the hardware differences.

We will not add results from thinner  sensors.

@rubinsky : Could you re-run your scripts and let us know? That would clearly be most efficient.

**Comment by rubinsky** [comment]
ok, thanks! I did not see them posted, I will have a look.

for rerunning the scripts: there is no point for me to rerun the scripts, only if you/Thomas will do it in your analysis chain and your plots will agree with mine.

**Comment by TCThenna** [comment]
I am not sure I understand well enough... 

Do you want to check that the cluster size as a function of the threshold for our 20 um sensors is the same as for your measurement with 20 um?

**Comment by simonspa** [comment]
Hi @rubinsky, we are not exactly sure which plot to look for. I guess you are talking about the folder in

```
/afs/desy.de/group/telescopes/documents/for_the_NIM_paper
```

But which one is the file we should look at? I'ts not really clear from your comment above: "cluster-size.vs.resolution.vs. threshold for different epi layer thickness"

Cheers,
Simon

**Comment by TCThenna** [comment]
@rubinsky , could you elaborate on your request?

**Comment by TCThenna** [comment]
The paper now reads:

The results reported here are based on data taken with $\Datura$ at test beam area~21 at {DESY-II} and with ACONITE at SLAC~ESTB and SPS~H6, but are applicable to other beam telescope copies with
the same sensor thickness~\cite{desy-tscopes-main}.
