### ISSUE TITLE
Comments by Emlyn

### ISSUE THREAD

**Issue by emlyn** [eudaq/StatusTelescope2015-Paper#9]
Very nice paper, and well written. I have only some minor corrections for typos and grammar tweaks:
- page 1, footnote 2: my affiliation should be "**_SwiftKey**_" (with capital K)
- page 2, line 15: "**_well suited**_" is more idiomatic than "well suitable".
- page 2, line 37: "From January 2013 until March 2014 **_alone**_, about ..."
- page 3, line 3: "80 ms, **_and**_ the"
- page 3, line 35: "This adds **_up**_ to a total"
- page 3, line 44: "equals 115.2 μs**_,**_ allowing for" (~~and~~)
- page 3, line 46: "the active area **_is estimated**_ to be " (~~estimates~~)
- page 3, line 51: should "pixel" be removed from the units? (For dimensional correctness, so that: 2·10<sup>-5</sup> per readout frame \* 4 Mpixels = 80 pixels per readout frame)
- page 4, line 1: "Lightproof Kapton foils" (remove comma)
- page 4, line 4: "The two telescope arms, usually [...] the DUT, **_are**_ movable" (~~is~~)
- page 4, line 25: "four PMT **_input**_ signals" (~~inputs~~)
- page 5, line 14: "trigger line: **_after**_ the trigger" (~~After~~)
- page 5, first paragraph: This describes the reset line as being an output from the TLU from the RJ45 connectors, but an input on the LEMO connectors, I don't remember the details of how the TLU works, but presumably one of these must be wrong?
- page 12, line 23: "the material budget at which" (remove comma)
- page 14, line 23: maybe "Structuring the European Research Area" should be enclosed in double quotes for clarity (and consistency with the AIDA one)?

**Comment by simonspa** [comment]
> page 3, line 51: should "pixel" be removed from the units? (For dimensional correctness, so that: 2·10-5 per readout frame \* 4 Mpixels = 80 pixels per readout frame)

I agree that formally the pixels should be removed from the unit, but I think it could help clarity when reading, not sure though.

> page 5, first paragraph: This describes the reset line as being an output from the TLU from the RJ45 connectors, but an input on the LEMO connectors, I don't remember the details of how the TLU works, but presumably one of these must be wrong?

For me this reads correct:

> the TLU provides RJ45 connectors with four LVDS pairs carrying the trigger clock, busy line, reset line, and trigger line. The trigger clock and the busy line are inputs to the TLU, whereas the reset and the trigger line are signals produced by the TLU. [...] In addition, a LEMO interface is available providing trigger output and inputs for the busy and reset signals.

Do you think there is any further need for clarification?

> page 14, line 23: maybe "Structuring the European Research Area" should be enclosed in double quotes for clarity (and consistency with the AIDA one)?

Apparently has been edited by someone already, making it consistent but by removing the double quotes...

**Comment by emlyn** [comment]
> > page 3, line 51: should "pixel" be removed from the units? (For dimensional correctness, so that: 2·10-5 per readout frame \* 4 Mpixels = 80 pixels per readout frame)
> 
> I agree that formally the pixels should be removed from the unit, but I think it could help clarity when reading, not sure though.

I agree that mentioning pixels somewhere would help with clarity, but in the units it is also a bit confusing, I initially read it as only one noise pixel per 50000 frames. How about something like: "the average noise occupancy **_per pixel**_ is measured to be smaller than 2·10<sup>-5</sup> per readout frame"?

> the TLU provides RJ45 connectors with four LVDS pairs carrying the trigger clock, busy line, reset line, and trigger line. The trigger clock and the busy line are inputs to the TLU, whereas the reset and the trigger line are signals produced by the TLU.

This says that the reset line is an output (signal produced by the TLU)

> In addition, a LEMO interface is available providing trigger output and inputs for the busy and reset signals.

But here it says the reset line is an input. Unless I'm misremembering how the TLU works, I believe this is wrong and should read something like "In addition, a LEMO interface is available providing trigger and reset outputs and an input for the busy signal."

**Comment by simonspa** [comment]
> How about something like: "the average noise occupancy per pixel is measured to be smaller than 2·10-5 per readout frame"?

This sounds very nice, I will change the text accordingly.

> Unless I'm misremembering how the TLU works, I believe this is wrong and should read something like "In addition, a LEMO interface is available providing trigger and reset outputs and an input for the busy signal."

Of course you are right, I really managed to read the above paragraph three times without noticing the obvious mistake... :) Thanks, will also correct this!
